score = max([M(length(firstString),length(secondString),firstString,secondString,d,e, blosom), ...
    GX(length(firstString),length(secondString),firstString,secondString,d,e,blosom), ...
    GY(length(firstString),length(secondString),firstString,secondString,d,e,blosom)]);